# michman: "spo-dev:7224"
michman: "localhost:9090"
name: "MyLovelyMac"
addr: "localhost"
port: "7070"
secret: "haslo"
db: "postgres://postgres:ssauthbasepsQKiw*@192.168.221.185:5432/postgres?sslmode=disable"
# db: "postgres://postgres:postgres@localhost:5432/divers_target?sslmode=disable"
